[package]
org = "shammi"
name = "book_marketplace"
version = "0.1.0"
distribution = "2201.11.0"

[build-options]
observabilityIncluded = true

[[tool.persist]]
id = "generate-db-client"
targetModule = "book_marketplace.data"
options.datastore = "inmemory"
filePath = "persist/model.bal"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist.inmemory-native"
version = "1.5.0"
