[package]
org = "wso2"
name = "book_marketplace"
version = "0.1.0"
distribution = "2201.11.0"

[build-options]
observabilityIncluded = true

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist.inmemory-native"
version = "1.5.0"
